In [1]:
#1.Debug the given code
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],  # 'Thirty' is not a valid number
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = df['Feature1'].astype(str)  # Error: Cannot convert 'Thirty' to int

print(df)



  Feature1  Feature2
0       10       5.5
1       20       6.7
2   Thirty       8.9


In [5]:
#2.
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value,inplace=True)  # Error: fillna() does not modify in place

print(df)


     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [19]:
#3.
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([1, 2, 3, 4, 5]).reshape(-1,1)  # Error: X should be 2D
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)


LinearRegression()

In [23]:
#4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50]).reshape(-1,1)  # Error: Should be 2D

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [33]:
#5.
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']  # Error: Labels should be numeric

encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)
print("Encoded labels:", y_encoded)

model = LogisticRegression()
model.fit(X, y)


Encoded labels: [1 0 1]


LogisticRegression()

In [53]:
#6.import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df['Category'].values.reshape(-1,1)) # Error: Data should be reshaped
print(encoded.toarray())


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [63]:
#6.
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0, 1]  # inconsistant number of samples (4,3)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [65]:
#7.from sklearn.linear_model import LogisticRegression

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels

encoder = LabelEncoder()
encoder.fit_transform(y_train)

model = LogisticRegression()
model.fit(X_train, y_train)


LogisticRegression()

In [87]:
#8.
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# Creating a dataset with missing values
#X_train = np.array([[1, 2], [3, np.nan], [5, 6]])

X_train = pd.DataFrame([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

X_train = X_train.fillna(0)

model = LinearRegression()
model.fit(X_train, y_train) 

print("X_train",X_train)


X_train    0  1
0  1  2
1  3  0
2  5  6


In [95]:
#9.
from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed

encoder = LabelEncoder()
label_encoder = encoder.fit_transform(y_train)

print("Encoded labels:", label_encoder)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)


Encoded labels: [1 0 1]


DecisionTreeClassifier()

In [147]:
#10.
from sklearn.svm import SVC

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

print("Scaled value \n", X_train_scaled)

model = SVC()
model.fit(X_train_scaled, y_train)

X_test_scaled = scaler.transform([[2,200]])
print(model.predict(X_test_scaled))  # Unreliable output due to large-scale difference


Scaled value 
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
[1]
